#!/usr/bin/env bash
# a bash script that displays a string indefinitly and prints another string when SIGTERM signal is captured
trap "echo I am invincible!!!" SIGTERM
i=1
while [ $i -lt 2 ]
do
	echo "To infinity and beyond"
	sleep 2
done
