#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20
x=1
while [ $x -le 20 ]
do
	case $x in
		4)
			printf "4\nbad luck from China\n"
			;;
		9)
			printf "9\nbad luck from Japan\n"
			;;
		17)
			printf "17\nbad luck from Italy\n"
			;;
		*)
			echo $x
			;;
	esac
	(( x++ ))
done
