#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20
x=1
while [ $x -le 20 ]
do
	if [ $x -eq 4 ]
	then
		echo 4
		echo bad luck from China
	elif [ $x -eq 9 ]
	then
		echo 9
		echo bad luck from Japan
	elif [ $x -eq 17 ]
	then
		echo 17
		echo bad luck from Italy
	else
		echo $x
	fi
	(( x++ ))
done
